/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StandingsRouteImport } from './routes/standings'
import { Route as PlayersRouteImport } from './routes/players'
import { Route as NewGameRouteImport } from './routes/new-game'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LocationsIndexRouteImport } from './routes/locations/index'
import { Route as GroupsIndexRouteImport } from './routes/groups/index'
import { Route as LocationsNewRouteImport } from './routes/locations/new'
import { Route as LocationsLocationIdRouteImport } from './routes/locations/$locationId'
import { Route as GroupsNewRouteImport } from './routes/groups/new'
import { Route as GroupsGroupIdRouteImport } from './routes/groups/$groupId'
import { Route as GamesGameIdRouteImport } from './routes/games.$gameId'
import { Route as GroupsGroupIdIndexRouteImport } from './routes/groups/$groupId/index'
import { Route as GroupsGroupIdLedgerRouteImport } from './routes/groups/$groupId/ledger'

const StandingsRoute = StandingsRouteImport.update({
  id: '/standings',
  path: '/standings',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayersRoute = PlayersRouteImport.update({
  id: '/players',
  path: '/players',
  getParentRoute: () => rootRouteImport,
} as any)
const NewGameRoute = NewGameRouteImport.update({
  id: '/new-game',
  path: '/new-game',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsIndexRoute = LocationsIndexRouteImport.update({
  id: '/locations/',
  path: '/locations/',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsIndexRoute = GroupsIndexRouteImport.update({
  id: '/groups/',
  path: '/groups/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsNewRoute = LocationsNewRouteImport.update({
  id: '/locations/new',
  path: '/locations/new',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsLocationIdRoute = LocationsLocationIdRouteImport.update({
  id: '/locations/$locationId',
  path: '/locations/$locationId',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsNewRoute = GroupsNewRouteImport.update({
  id: '/groups/new',
  path: '/groups/new',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsGroupIdRoute = GroupsGroupIdRouteImport.update({
  id: '/groups/$groupId',
  path: '/groups/$groupId',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesGameIdRoute = GamesGameIdRouteImport.update({
  id: '/games/$gameId',
  path: '/games/$gameId',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsGroupIdIndexRoute = GroupsGroupIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GroupsGroupIdRoute,
} as any)
const GroupsGroupIdLedgerRoute = GroupsGroupIdLedgerRouteImport.update({
  id: '/ledger',
  path: '/ledger',
  getParentRoute: () => GroupsGroupIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/new-game': typeof NewGameRoute
  '/players': typeof PlayersRoute
  '/standings': typeof StandingsRoute
  '/games/$gameId': typeof GamesGameIdRoute
  '/groups/$groupId': typeof GroupsGroupIdRouteWithChildren
  '/groups/new': typeof GroupsNewRoute
  '/locations/$locationId': typeof LocationsLocationIdRoute
  '/locations/new': typeof LocationsNewRoute
  '/groups/': typeof GroupsIndexRoute
  '/locations/': typeof LocationsIndexRoute
  '/groups/$groupId/ledger': typeof GroupsGroupIdLedgerRoute
  '/groups/$groupId/': typeof GroupsGroupIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/new-game': typeof NewGameRoute
  '/players': typeof PlayersRoute
  '/standings': typeof StandingsRoute
  '/games/$gameId': typeof GamesGameIdRoute
  '/groups/new': typeof GroupsNewRoute
  '/locations/$locationId': typeof LocationsLocationIdRoute
  '/locations/new': typeof LocationsNewRoute
  '/groups': typeof GroupsIndexRoute
  '/locations': typeof LocationsIndexRoute
  '/groups/$groupId/ledger': typeof GroupsGroupIdLedgerRoute
  '/groups/$groupId': typeof GroupsGroupIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/history': typeof HistoryRoute
  '/new-game': typeof NewGameRoute
  '/players': typeof PlayersRoute
  '/standings': typeof StandingsRoute
  '/games/$gameId': typeof GamesGameIdRoute
  '/groups/$groupId': typeof GroupsGroupIdRouteWithChildren
  '/groups/new': typeof GroupsNewRoute
  '/locations/$locationId': typeof LocationsLocationIdRoute
  '/locations/new': typeof LocationsNewRoute
  '/groups/': typeof GroupsIndexRoute
  '/locations/': typeof LocationsIndexRoute
  '/groups/$groupId/ledger': typeof GroupsGroupIdLedgerRoute
  '/groups/$groupId/': typeof GroupsGroupIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/history'
    | '/new-game'
    | '/players'
    | '/standings'
    | '/games/$gameId'
    | '/groups/$groupId'
    | '/groups/new'
    | '/locations/$locationId'
    | '/locations/new'
    | '/groups/'
    | '/locations/'
    | '/groups/$groupId/ledger'
    | '/groups/$groupId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/history'
    | '/new-game'
    | '/players'
    | '/standings'
    | '/games/$gameId'
    | '/groups/new'
    | '/locations/$locationId'
    | '/locations/new'
    | '/groups'
    | '/locations'
    | '/groups/$groupId/ledger'
    | '/groups/$groupId'
  id:
    | '__root__'
    | '/'
    | '/history'
    | '/new-game'
    | '/players'
    | '/standings'
    | '/games/$gameId'
    | '/groups/$groupId'
    | '/groups/new'
    | '/locations/$locationId'
    | '/locations/new'
    | '/groups/'
    | '/locations/'
    | '/groups/$groupId/ledger'
    | '/groups/$groupId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HistoryRoute: typeof HistoryRoute
  NewGameRoute: typeof NewGameRoute
  PlayersRoute: typeof PlayersRoute
  StandingsRoute: typeof StandingsRoute
  GamesGameIdRoute: typeof GamesGameIdRoute
  GroupsGroupIdRoute: typeof GroupsGroupIdRouteWithChildren
  GroupsNewRoute: typeof GroupsNewRoute
  LocationsLocationIdRoute: typeof LocationsLocationIdRoute
  LocationsNewRoute: typeof LocationsNewRoute
  GroupsIndexRoute: typeof GroupsIndexRoute
  LocationsIndexRoute: typeof LocationsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/standings': {
      id: '/standings'
      path: '/standings'
      fullPath: '/standings'
      preLoaderRoute: typeof StandingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/players': {
      id: '/players'
      path: '/players'
      fullPath: '/players'
      preLoaderRoute: typeof PlayersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new-game': {
      id: '/new-game'
      path: '/new-game'
      fullPath: '/new-game'
      preLoaderRoute: typeof NewGameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/': {
      id: '/locations/'
      path: '/locations'
      fullPath: '/locations/'
      preLoaderRoute: typeof LocationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/': {
      id: '/groups/'
      path: '/groups'
      fullPath: '/groups/'
      preLoaderRoute: typeof GroupsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/new': {
      id: '/locations/new'
      path: '/locations/new'
      fullPath: '/locations/new'
      preLoaderRoute: typeof LocationsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/$locationId': {
      id: '/locations/$locationId'
      path: '/locations/$locationId'
      fullPath: '/locations/$locationId'
      preLoaderRoute: typeof LocationsLocationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/new': {
      id: '/groups/new'
      path: '/groups/new'
      fullPath: '/groups/new'
      preLoaderRoute: typeof GroupsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/$groupId': {
      id: '/groups/$groupId'
      path: '/groups/$groupId'
      fullPath: '/groups/$groupId'
      preLoaderRoute: typeof GroupsGroupIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/$gameId': {
      id: '/games/$gameId'
      path: '/games/$gameId'
      fullPath: '/games/$gameId'
      preLoaderRoute: typeof GamesGameIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups/$groupId/': {
      id: '/groups/$groupId/'
      path: '/'
      fullPath: '/groups/$groupId/'
      preLoaderRoute: typeof GroupsGroupIdIndexRouteImport
      parentRoute: typeof GroupsGroupIdRoute
    }
    '/groups/$groupId/ledger': {
      id: '/groups/$groupId/ledger'
      path: '/ledger'
      fullPath: '/groups/$groupId/ledger'
      preLoaderRoute: typeof GroupsGroupIdLedgerRouteImport
      parentRoute: typeof GroupsGroupIdRoute
    }
  }
}

interface GroupsGroupIdRouteChildren {
  GroupsGroupIdLedgerRoute: typeof GroupsGroupIdLedgerRoute
  GroupsGroupIdIndexRoute: typeof GroupsGroupIdIndexRoute
}

const GroupsGroupIdRouteChildren: GroupsGroupIdRouteChildren = {
  GroupsGroupIdLedgerRoute: GroupsGroupIdLedgerRoute,
  GroupsGroupIdIndexRoute: GroupsGroupIdIndexRoute,
}

const GroupsGroupIdRouteWithChildren = GroupsGroupIdRoute._addFileChildren(
  GroupsGroupIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HistoryRoute: HistoryRoute,
  NewGameRoute: NewGameRoute,
  PlayersRoute: PlayersRoute,
  StandingsRoute: StandingsRoute,
  GamesGameIdRoute: GamesGameIdRoute,
  GroupsGroupIdRoute: GroupsGroupIdRouteWithChildren,
  GroupsNewRoute: GroupsNewRoute,
  LocationsLocationIdRoute: LocationsLocationIdRoute,
  LocationsNewRoute: LocationsNewRoute,
  GroupsIndexRoute: GroupsIndexRoute,
  LocationsIndexRoute: LocationsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
